import { z } from "zod";

/**
 * Canonical Plant schema for @aquascape/data.
 *
 * Follows the botany-agent `plant-data-schema` skill. Every field that
 * downstream agents (sim, render, app) consume is explicit and required;
 * truly-unknown numeric fields are modeled as `number | null` with an
 * explanation in `notes`.
 *
 * If you need a new field, do NOT edit this file — open an issue so the
 * orchestrator can propagate the change across sim/render/app consumers.
 */

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export const growthFormEnum = z.enum([
  "stem",
  "rosette",
  "carpeting",
  "epiphyte",
  "moss",
  "floating",
  "rhizome",
]);

export const placementEnum = z.enum([
  "foreground",
  "midground",
  "background",
  "attached",
  "floating",
]);

export const propagationEnum = z.enum([
  "topping",
  "side-shoots",
  "runners",
  "rhizome-division",
  "adventitious-plantlets",
  "spores",
  "fragmentation",
  "seed",
]);

export const growthRateEnum = z.enum(["slow", "medium", "fast"]);

export const difficultyLabelEnum = z.enum(["easy", "medium", "hard", "expert"]);

export const licenseEnum = z.enum([
  "CC0-1.0",
  "CC-BY-4.0",
  "CC-BY-SA-4.0",
  "CC-BY-3.0",
  "CC-BY-SA-3.0",
  "original",
  "needs-replacement",
]);

// ---------------------------------------------------------------------------
// Sub-schemas
// ---------------------------------------------------------------------------

const range = z.object({
  min: z.number().nullable(),
  opt: z.number().nullable(),
  max: z.number().nullable(),
});

const rangeWithUnit = range.extend({
  unit: z.string(),
});

const commonNames = z.object({
  en: z.array(z.string()).min(1),
  zh: z.array(z.string()).min(1),
});

const envelope = z.object({
  light: rangeWithUnit, // µmol/m²/s (PAR)
  co2: rangeWithUnit, // ppm
  temperatureC: range, // °C
  pH: range, // unitless
  gh: range, // °dGH
  kh: range, // °dKH
  tdsPpm: range.optional(),
});

const nutrients = z.object({
  macros: z.object({
    nitrogenDemand: z.enum(["low", "medium", "high"]),
    phosphorusDemand: z.enum(["low", "medium", "high"]),
    potassiumDemand: z.enum(["low", "medium", "high"]),
  }),
  micros: z.object({
    ironDemand: z.enum(["low", "medium", "high"]),
    traceDemand: z.enum(["low", "medium", "high"]),
  }),
  rootFeeder: z.boolean(),
  waterColumnFeeder: z.boolean(),
});

const growth = z.object({
  rate: growthRateEnum,
  maxHeightCm: z.number().positive(),
  maxSpreadCm: z.number().positive(),
  internodeCm: z.number().positive().nullable(),
  propagation: z.array(propagationEnum).min(1),
});

/**
 * Sim-consumable coefficients. These are intentionally first-order;
 * sim-agent will calibrate them against empirical growth curves.
 *
 *   photosynthesisRate(light, co2, T) ≈
 *       k_photosynthesis
 *     * saturating(light / k_light)
 *     * saturating(co2   / k_co2)
 *     * gaussian(T; preferred_temp_c, temp_tolerance_c)
 */
const simCoefficients = z.object({
  k_photosynthesis: z.number().positive(), // relative units, 1.0 = Rotala rotundifolia reference
  k_light: z.number().positive(), // µmol/m²/s — half-saturation PAR
  k_co2: z.number().positive(), // ppm        — half-saturation CO2
  preferred_temp_c: z.number(),
  temp_tolerance_c: z.number().positive(), // 1-sigma band around preferred_temp_c
});

const image = z.object({
  src: z.string(), // URL or repo-relative path
  license: licenseEnum,
  credit: z.string(),
  sourceUrl: z.string().url().optional(),
});

// ---------------------------------------------------------------------------
// Plant
// ---------------------------------------------------------------------------

export const plantSchema = z.object({
  id: z
    .string()
    .regex(/^[a-z0-9]+(-[a-z0-9]+)*$/, "id must be kebab-case"),
  scientificName: z.string().min(3),
  family: z.string().min(3),
  taxonomy: z.object({
    kingdom: z.string(),
    phylum: z.string(),
    class: z.string(),
    order: z.string(),
    family: z.string(),
    genus: z.string(),
    species: z.string(),
    cultivar: z.string().optional(),
  }),
  commonNames,
  pinyin: z.array(z.string()).min(1), // tones-stripped pinyin for fuzzy search
  group: growthFormEnum,
  growthForm: growthFormEnum,
  origin: z.array(z.string()).min(1),
  difficulty: z.number().int().min(1).max(5), // 1 = beginner, 5 = expert
  difficultyLabel: difficultyLabelEnum,
  envelope,
  nutrients,
  growth,
  placement: z.array(placementEnum).min(1),
  colorRange: z.array(z.string()).min(1), // descriptive tags, e.g. "green", "red-high-light"
  colorHex: z.string().regex(/^#[0-9a-fA-F]{6}$/), // color under good conditions
  sim: simCoefficients,
  notes: z.string().min(1),
  images: z.array(image), // may be empty if no CC-BY/original asset yet
  citations: z.array(z.string()).min(1),
});

export type Plant = z.infer<typeof plantSchema>;
export const plantArraySchema = z.array(plantSchema);
